apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "cm-zk-%s" .Release.Name | trunc 24 }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-zk" .Release.Name | trunc 24 }}"
    role: zookeeper
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
data:
  tick: "{{.Values.TickTimeMs}}"
  init: "{{.Values.InitTicks}}"
  sync: "{{.Values.SyncTicks}}"
  client.cnxns: "{{.Values.ClientCnxns}}"
  snap.retain: "{{.Values.SnapRetain}}"
  purge.interval: "{{.Values.PurgeHours}}"
  log.level: {{.Values.LogLevel}}
