apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{ printf "zk-%s" .Release.Name }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-zk" .Release.Name }}"
    role: zookeeper
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  serviceName: "{{ printf "hs-zk-%s" .Release.Name | trunc 63}}"
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  replicas: {{.Values.Servers}}
  template:
    metadata:
      labels:
        app: {{.Release.Name | quote }}
        component: "{{ printf "%s-zk" .Release.Name }}"
        role: zookeeper
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      {{- if eq .Values.AntiAffinity "hard"}}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: component
                  operator: In
                  values:
                    - "{{ printf "%s-zk" .Release.Name }}"
            topologyKey: kubernetes.io/hostname
      {{- else if eq .Values.AntiAffinity "soft"}}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - "{{ printf "%s-zk" .Release.Name }}"
                topologyKey: kubernetes.io/hostname
      {{- end}}
      tolerations:
        - key: "dedicated"
          value: "{{ .Values.DedicatedToleration }}"
      containers:
      - name: k8szk
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        image: {{ .Values.Image}}:{{ .Values.Tag }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        ports:
        - containerPort: {{.Values.ClientPort}}
          name: client
        - containerPort: {{.Values.ServerPort}}
          name: server
        - containerPort: {{.Values.LeaderElectionPort}}
          name: leader-election
        env:
        - name : ZK_REPLICAS
          value: "{{.Values.Servers}}"
        - name : ZK_TICK_TIME
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "cm-zk-%s" .Release.Name }}"
                key: tick
        - name : ZK_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "cm-zk-%s" .Release.Name }}"
                key: init
        - name : ZK_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "cm-zk-%s" .Release.Name }}"
                key: tick
        - name : ZK_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "cm-zk-%s" .Release.Name }}"
                key: client.cnxns
        - name: ZK_SNAP_RETAIN_COUNT
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "cm-zk-%s" .Release.Name }}"
                key: snap.retain
        - name: ZK_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "cm-zk-%s" .Release.Name }}"
                key: purge.interval
        - name: ZK_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
                name: "{{ printf "cm-zk-%s" .Release.Name }}"
                key: log.level
        - name: ZK_CLIENT_PORT
          value: "{{.Values.ClientPort}}"
        - name: ZK_SERVER_PORT
          value: "{{.Values.ServerPort}}"
        - name: ZK_ELECTION_PORT
          value: "{{.Values.LeaderElectionPort}}"
        - name: SERVER_JVMFLAGS
          value: "-server -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XshowSettings:vm -XX:MaxRAMFraction=1"
        command:
        - sh
        - -c
        - zkGenConfig.sh && exec zkServer.sh start-foreground
        readinessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: {{.Values.ProbeInitialDelaySeconds}}
          timeoutSeconds: {{.Values.ProbeTimeoutSeconds}}
        livenessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: {{.Values.ProbeInitialDelaySeconds}}
          timeoutSeconds: {{.Values.ProbeTimeoutSeconds}}
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
      labels:
        app: {{.Release.Name | quote }}
        component: "{{ printf "%s-zk" .Release.Name }}"
        role: zookeeper
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      annotations:
        {{- if .Values.StorageClass}}
        volume.beta.kubernetes.io/storage-class: {{.Values.StorageClass | quote}}
        {{- else}}
        volume.alpha.kubernetes.io/storage-class: "default"
        {{- end}}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{.Values.Storage}}
