apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "hs-zk-%s" .Release.Name | trunc 63 }}"
  labels:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-zk" .Release.Name }}"
    role: zookeeper
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: {{.Values.ServerPort}}
    name: server
  - port: {{.Values.LeaderElectionPort}}
    name: leader-election
  clusterIP: None
  selector:
    component: "{{ printf "%s-zk" .Release.Name }}"
    role: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "zk-%s" .Release.Name | trunc 63 }}"
  labels:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-zk" .Release.Name }}"
    role: zookeeper
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: {{.Values.ClientPort}}
    name: client
  selector:
    component: "{{ printf "%s-zk" .Release.Name }}"
    role: zookeeper
