# Default values for datomic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: 997690819742.dkr.ecr.us-east-1.amazonaws.com/datomic
  tag: 0.0.11
  pullPolicy: "IfNotPresent"
HeapRatio: 70
TableRegion: "us-east-1"
Protocol: ddb
TransactorRole: datomic-aws-transactor
PeerRole: datomic-aws-peer
Replicas: 1
DynamoDBTable: ""
#MemcachedServers: memcached-cluster-0:112211,memcached-cluster-1:112211
resources:
  requests:
    memory: 100m
    cpu: 512Mi
  limits:
    memory: 4Gi
    cpu: 2
