apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "cm-kf-%s" .Release.Name | trunc 24 }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}"
server.properties:
  tick: "{{.Values.TickTimeMs}}"
