apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ printf "%s-%s" .Chart.Name .Release.Name  }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-%s" .Release.Name .Chart.Name }}"
    role: datomic
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: {{ .Values.Replicas }}
  template:
    metadata:
      labels:
        app: {{.Release.Name | quote }}
        component: "{{ printf "%s-%s" .Release.Name .Chart.Name }}"
        role: datomic
    spec:
      containers:
      - name: datomic
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - "./datomicRun.sh"
          - "/etc/config/transactor.properties"
        volumeMounts:
          - name: data
            mountPath: /etc/data
          - name: config
            mountPath: /etc/config
        ports:
          - containerPort: 4334
        env:
          - name : JAVA_MAX_MEM_RATIO
            value: "{{.Values.HeapRatio}}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: "{{ printf "cm-%s-%s" .Chart.Name .Release.Name }}"
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "cm-%s-%s" .Chart.Name .Release.Name }}"
  labels:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-%s" .Release.Name .Chart.Name }}"
    role: datomic
data:
  transactor.properties: |-
    protocol={{ .Values.Protocol }}
    host=0.0.0.0
    port=4334
    alt-host={{ printf "%s-%s" .Chart.Name .Release.Name | trunc 63 }}

    license-key={{ .Values.LicenseKey }}

    aws-dynamodb-table={{ .Values.DynamoDBTable }}

    {{ if .Values.TableRegion }}
    aws-dynamodb-region={{ .Values.TableRegion }}
    {{ end }}

    {{ if .Values.OverrideEndpoint }}
    aws-dynamodb-override-endpoint={{ .Values.OverrideEndpoint }}
    {{ end }}
    aws-transactor-role={{ .Values.TransactorRole }}
    aws-peer-role={{ .Values.TransactorRole }}
    memory-index-threshold=32m
    memory-index-max=256m
    object-cache-max=128m
    pid-file=/transactor.pid

    # Memcached configuration.
    {{ if .Values.MemcachedServers }}
    memcached={{ .Values.MemcachedServers }}
    {{ end }}
