apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "%s-%s" .Values.ServicePrefix .Release.Name | trunc 63 }}"
  labels:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-memcached" .Release.Name | trunc 24 }}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    role: memcached
spec:
  clusterIP: None
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
  selector:
    app: {{.Release.Name | quote }}
    component: "{{ printf "%s-memcached" .Release.Name | trunc 24 }}"
