Name: "kf"
Replicas: 3
Image: "onyxplatform/kafka"
ImageTag: 11
ImagePullPolicy: "Always"
ramFraction: 2
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 200m
Storage: "1Gi"
DataDirectory: "/opt/kafka/data"
TopicDeleteEnabled: true
Component: "kafka"
UncleanLeaderElection: false
AutoCreateTopicsEnable: false
LogRetentionCheckIntervalMs: 15000
AntiAffinity: "soft"
DedicatedToleration: "kafka-zookeeper"
DiskMonitorSidecar:
  Image: gardnervickers/prometheus-ebs-metrics
  ImageTag: latest
zookeeper:
  provide: true
# hostname:
## Prometheus Service Monitor
# ServiceMonitor:
#   JobLabelPrefix: "kf"
#   Interval: 15s
#   Namespace: <defaults to monitoring>
