Name: "kf"
Replicas: 3
Image: "onyxplatform/kafka"
ImageTag: "6"
ImagePullPolicy: "Always"
Cpu: "100m"
Memory: "512Mi"
MaxCpu: "200m"
MaxMemory: "1024Mi"
HeapRatio: 70
Storage: "1Gi"
DataDirectory: "/opt/kafka/data"
TopicDeleteEnabled: true
Component: "kafka"
UncleanLeaderElection: false
# zookeeper:
#   Name: "zk"
#   Component: "zk"
AntiAffinity: "soft"
DedicatedToleration: "kafka-zookeeper"
DiskMonitorSidecar:
  Image: gardnervickers/prometheus-ebs-metrics
  ImageTag: latest

## Prometheus Service Monitor
# ServiceMonitor:
#   JobLabelPrefix: "kf"
#   Interval: 15s
#   Namespace: <defaults to monitoring>
