apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Release.Name }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
data:
  common.rules: |-
    {{ if .Values.K8sPodRestartingTooMuch }}
    ALERT K8sPodRestartingTooMuch
      IF sum (rate(kube_pod_container_status_restarts[5m]) > 0) BY(job, exported_pod, instance, namespace)
      FOR 10m
      LABELS {
        service = "k8s",
        severity = "warning",
      }
      ANNOTATIONS {
        summary = "Pod is in a restart loop",
        description = "Pod {{ $labels.namespace }}/{{ $labels.exported_pod }} is restarting constantly",
      }
    {{ end }}
