# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
Image: onyxplatform/k8szk
Tag: 19
Servers: 3
Cpu: "100m"
Memory: "512Mi"
resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 100m
Storage: "50Gi"
StorageClass : default
ServerPort: 2888
LeaderElectionPort: 3888
ClientPort: 2181
ImagePullPolicy: "Always"
TickTimeMs: 2000
InitTicks: 10
SyncTicks: 5
ClientCnxns: 60
SnapRetain: 3
PurgeHours: 1
ProbeInitialDelaySeconds : 15
ProbeTimeoutSeconds : 5
AntiAffinity : "hard"
LogLevel : "INFO"
DedicatedToleration: "kafka-zookeeper"
